all: main.c
$ make       // Creates a makefile which has main.c as its dependency

all: main.c
    gcc main.c -o main
$ make       // Creates a makefile which has main.c as its dependency
                and compiles main.c into executable named main

clean:
    rm main
$ make clean                // Deletes the executable file named main

all: object1.o object2.o object3.o    // Will compile executable only
    gcc object1.o object2.o object3.o    if all required object files
                                         are present

all: cube.o rectangle.o cylinder.o circle.o
    gcc -o shapes cube.o rectangle.o cylinder.o circle.o
                    // Compiles the object files into an executable
                       named shapes

cube.o: main1.c main2.c main3.c
    gcc -c main1.c main2.c main3.c  // Dependency rules to combine .c
                                    files into each object file

$@ => Name of the file to be made (current target)
$? => Name of the changed dependencies (changed more recently than
      current target)
$< => Name of the related file that caused action (current
      dependency)
$* => Prefix shared by target and dependent files (current
      dependency without extension)
